version: '3.3'

services:
  app_db:
    build: ./db_api
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - ./db_api:/app
    links:
      - db
    environment:
      - API_KEY=dW4gY2hpc3Rl
      - API_KEY_NAME=key
  app_df:
    build: ./df_api
    command: python -u app.py
    ports:
      - "8000:8000"
    volumes:
      - ./df_api:/app
    links:
      - db
    environment:
      - API_KEY=dW4gY2hpc3Rl
      - API_KEY_NAME=key
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=face_recognition_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017

  admin_ui:
    build: ./admin_ui
    command: node app.js
    ports:
      - "5001:4000"
    volumes:
      - ./admin_ui:/app
      - /app/node_modules
