version: '3.3'

volume:
  html:
  vhostd:
  mongodbdata:
  appdb:

networks:
  fa-back:

services:
  app:
    container_name: faceapp
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - appdb:/app/db
    links:
      - db
    networks:
      - fa-back

  db:
    container_name: mongodb
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=face_recognition_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
    networks:
      - wp-back

  nginx-proxy:
    container_name: nginx_proxy
    depends_on:
      - faceapp
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certificates:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - fa-back

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./certificates:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro








